### ISSUE TITLE
Save directly to local drive

### ISSUE THREAD

**Issue by commit4ever** [adrienbrault/hf-gguf-to-ollama#1]
Hi 

Thanks a lot for releasing this !
Is there any way to make the push to Ollama optional and just save to the local drive? 

Aisee

**Comment by adrienbrault** [comment]
Hey, that's a good idea!

Implemented in https://github.com/adrienbrault/hf-gguf-to-ollama/commit/979af903c4350a3148de64b3d8ab13443f9b0825

Please let me know if you run into issues
